In [4]:
import os

import pandas as pd
import numpy as np

In [5]:
def export_to_csv(data_frame, file_name):
    """
    Export a DataFrame to a CSV file.

    Parameters:
        - data_frame: pandas DataFrame
        - file_name: str, name of the CSV file (without the extension)
    """
    #print date stamp - datetime.datetime.now()
    
    #t_stamp = str(datetime.datetime.now()).split(".")[0].replace(" ","_")
    
    file_path = f"{file_name}.csv"
    
    data_frame.to_csv(file_path, index=False)
    print(f"DataFrame successfully exported to {file_path}")

In [6]:
pwd

'/Users/Moni/Ironhack/my_ironhack/projects/final-project/notebooks'

# TABLA HISTORICO DE PEDIDOS

In [12]:
df_f = pd.read_csv("../../data/history-pruchase-family.csv")
df_f["user"] = "family"

In [13]:
df_k = pd.read_csv("../../data/history-pruchase-kike.csv")
df_k["user"] = "kike"

In [14]:
df_p = pd.read_csv("../../data/history-pruchase-palacet.csv")
df_p["user"] = "palacet"

In [15]:
df = pd.concat([df_f, df_k,df_p])

In [16]:
df

,description,units,price_eu,unit_price,date,order_num,user
0,Jamón serrano Incarlopsa lonchas,1,3.49,3.49,2020-01-10,302316,family
1,Queso fresco de cabra Hacendado,1,2.20,2.20,2020-01-10,302316,family
2,Queso rallado 4 quesos Hacendado,1,1.59,1.59,2020-01-10,302316,family
3,Perlas de mozzarella fresca Hacendado,1,1.70,1.70,2020-01-10,302316,family
4,Mozzarella di bufala campana Hacendado,1,1.70,1.70,2020-01-10,302316,family
...,...,...,...,...,...,...,...
124,Activador del lavado ropa blanca Bosque Verde ...,1,1.60,1.60,2020-07-11,6947878,palacet
125,Suavizante ropa talco Bosque Verde concentrado,2,3.58,1.79,2020-07-11,6947878,palacet
126,Lavavajillas aloe Bosque Verde concentrado,1,1.55,1.55,2020-07-11,6947878,palacet
127,Lejía con detergente Bosque Verde,1,0.71,0.71,2020-07-11,6947878,palacet
128,Friegasuelos pino Bosque Verde líquido,1,0.65,0.65,2020-07-11,6947878,palacet

In [ ]:
OJO CON LAS MAYUSCULAS/MINUSCULAS:

Aceite de oliva virgen Hacendado
Aceite de oliva virgen extra Hacendado


Aguacates
Aguacate

Lenteja cocida Hacendado
Lenteja cocida pardina Hacendado

In [18]:
export_to_csv(df, "../../data/history-purchase")

DataFrame successfully exported to ../../data/history-purchase.csv

# TABLA PRODUCTO:

In [33]:
df_k

NameError: name 'df_k' is not defined

In [31]:
df_23 = pd.read_csv("../data/Mercadona Scraping 2023-03-11_21-39-33.csv", delimiter="~")

In [32]:
df_23

,product,product_type,product_volume,product_price_per_unit,product_price,product_unit,product_category,product_subcategory,product_url,product_code,collected_timestamp
0,"Aceite de oliva 0,4º Hacendado",Garrafa,5 L,"| 4,726 €/L",23.63,/ud.,"Aceite, especias y salsas >","Aceite, vinagre y sal",https://tienda.mercadona.es/product/4241/aceit...,4241.0,2023-03-11 21:46:34.649336
1,"Aceite de oliva 0,4º Hacendado",Botella,1 L,"| 4,77 €/L",4.77,/ud.,"Aceite, especias y salsas >","Aceite, vinagre y sal",https://tienda.mercadona.es/product/4240/aceit...,4240.0,2023-03-11 21:46:35.305827
2,Aceite de oliva virgen extra Hacendado,Garrafa,3 L,"| 5,584 €/L",16.75,/ud.,"Aceite, especias y salsas >","Aceite, vinagre y sal",https://tienda.mercadona.es/product/4717/aceit...,4717.0,2023-03-11 21:46:35.818152
3,Aceite de oliva virgen extra Hacendado,Botella,1 L,"| 5,63 €/L",5.63,/ud.,"Aceite, especias y salsas >","Aceite, vinagre y sal",https://tienda.mercadona.es/product/4740/aceit...,4740.0,2023-03-11 21:46:36.352894
4,Aceite de oliva virgen extra Hacendado Gran Se...,Botella,750 ml,"| 6,814 €/L",5.11,/ud.,"Aceite, especias y salsas >","Aceite, vinagre y sal",https://tienda.mercadona.es/product/4706/aceit...,4706.0,2023-03-11 21:46:36.951563
...,...,...,...,...,...,...,...,...,...,...,...
5224,Bebida de pomelo Hacendado sin azúcares añadidos,Not available,Not available,Not available,1.25,/ud.,Not Available,Compartir,https://tienda.mercadona.es/product/39604/bebi...,39604.0,2023-03-12 10:05:44.970111
5225,Bebida guayaba Hacendado sin azúcares añadidos,Not available,Not available,Not available,1.30,/ud.,Not Available,Compartir,https://tienda.mercadona.es/product/39659/bebi...,39659.0,2023-03-12 10:05:45.366446
5226,Bebida de pera Hacendado sin azúcares añadidos,Not available,Not available,Not available,1.10,/ud.,Not Available,Compartir,https://tienda.mercadona.es/product/39628/bebi...,39628.0,2023-03-12 10:05:45.766966
5227,Zumo de pomelo Hacendado,Not available,Not available,Not available,1.45,/ud.,Not Available,Compartir,https://tienda.mercadona.es/product/39696/zumo...,39696.0,2023-03-12 10:05:46.170104
5228,Zumo de manzana selección Hacendado,Not available,Not available,Not available,1.50,/ud.,Not Available,Compartir,https://tienda.mercadona.es/product/39922/zumo...,39922.0,2023-03-12 10:05:46.515096

In [28]:
df = df_23[["product", "product_price"]]

In [29]:
df

                                                product  product_price
0                        Aceite de oliva 0,4º Hacendado          23.63
1                        Aceite de oliva 0,4º Hacendado           4.77
2                Aceite de oliva virgen extra Hacendado          16.75
3                Aceite de oliva virgen extra Hacendado           5.63
4     Aceite de oliva virgen extra Hacendado Gran Se...           5.11
...                                                 ...            ...
5224   Bebida de pomelo Hacendado sin azúcares añadidos           1.25
5225     Bebida guayaba Hacendado sin azúcares añadidos           1.30
5226     Bebida de pera Hacendado sin azúcares añadidos           1.10
5227                           Zumo de pomelo Hacendado           1.45
5228                Zumo de manzana selección Hacendado           1.50

[5229 rows x 2 columns]

In [27]:
duplis = df[df.duplicated(subset=['product'])]

                                                product  product_price
1                        Aceite de oliva 0,4º Hacendado           4.77
3                Aceite de oliva virgen extra Hacendado           5.63
6                          Aceite de oliva 1º Hacendado           4.77
8                      Aceite de oliva virgen Hacendado           5.20
9                Aceite de oliva virgen extra Hacendado           2.34
...                                                 ...            ...
5209                        Zumo pura naranja Hacendado           2.20
5212                Zumo de naranja selección Hacendado           2.00
5216  Bebida de naranja Hacendado sin azúcares añadidos           1.50
5219                           Zumo de tomate Hacendado           1.40
5221                          Zumo de manzana Hacendado           1.12

[717 rows x 2 columns]

In [30]:
df_24 = pd.read_csv("../data/srape-mercadona_2024-03-08.csv")
df_24.head(10)

,categoria,subcategoria,descripcion,unidades,precio
0,Agua y refrescos,Isotónico y energético,Bebida isotónica limón Aquarius,8 latas x 330 ml,"6,80 €6,24 € /pack"
1,Agua y refrescos,Isotónico y energético,Bebida isotónica limón Aquarius,8 latas x 330 ml,"6,80 €6,24 € /pack"
2,"Aceite, especias y salsas","Aceite, vinagre y sal","Aceite de oliva 0,4º Hacendado",Botella 1 L,"9,25 € /ud."
3,"Aceite, especias y salsas","Aceite, vinagre y sal",Aceite de oliva virgen extra Hacendado,Garrafa 3 L,"29,55 € /ud."
4,"Aceite, especias y salsas","Aceite, vinagre y sal",Aceite de oliva virgen extra Hacendado,Botella 1 L,"9,90 € /ud."
5,"Aceite, especias y salsas","Aceite, vinagre y sal",Aceite de oliva virgen extra Hacendado Gran Se...,Botella 750 ml,"8,10 € /ud."
6,"Aceite, especias y salsas","Aceite, vinagre y sal",Aceite de oliva 1º Hacendado,Botella 1 L,"9,25 € /ud."
7,"Aceite, especias y salsas","Aceite, vinagre y sal",Aceite de oliva virgen Hacendado,Garrafa 3 L,"28,50 € /ud."
8,"Aceite, especias y salsas","Aceite, vinagre y sal",Aceite de oliva virgen Hacendado,Botella 1 L,"9,55 € /ud."
9,"Aceite, especias y salsas","Aceite, vinagre y sal",Aceite de oliva suave Hacendado,Garrafa 3 L,"27,60 € /ud."

# TABLA PRODUCT INFO (POR FEHCAS)

### Set up SQL connection
First we load the ".env" file so that we can load the user's secret log in info to SQL.

In [ ]:
password = os.getenv("sql_password")
dbName = 'mercadona'
connectionData=f"mysql+pymysql://root:{password}@localhost/{dbName}"
engine = alch.create_engine(connectionData)
engine